### PR TITLE
auto_cal batch file not saving logs when running as Admin

### PR DESCRIPTION
**Pull request by ReadZead**
hi, so for a while now I've only used the batch file as normal, until the other day I reread through the readme, since I recently got a glass bed for the printer, and noticed you suggested to run that as an administrator, and I noticed two major differences between running it as an administrator and when not, them being that when I run it without the permissions it does everything just fine except that it doesn't change the Z offset, with admin permissions it changes the Z offset, but doesn't write pass logs

### CODE REVIEW

**Comment by PurpleHullPeas** [comment]
I just now stumbled across this. I see what you're talking about with the logs, bit what do you mean by z-offset? This script does not modify M851.

**Comment by ReadZead** [comment]
Not the z-offset, I meant the Z endstop

**Comment by PurpleHullPeas** [comment]
As a workaround, you can run the program as an administrator, save your M666/M665 values, and then send G29 P5 V4 over USB for stock firmware to generate your values for the heat map. 

Doing some searching seems to suggest that this has something to do with converting the Python script from a .py file to a .exe file. I.E., the code works fine if ran as a Python script, but some features are not working from the batch file. I don't want to make any promises as to when this will get fixed, because the python compiler stuff is mostly based on stuff that I Googled and I don't have a super great understanding as to how/why it works that way.

I'm going to leave this here as a note to myself whenever I get some time to check on it.
https://www.reddit.com/r/learnpython/comments/8i0zqe/pyinstaller_cant_find_text_file/

Thanks for the report.

**Comment by PurpleHullPeas** [comment]
I believe I have fixed the problem. Please note that the batch file is simply a driver for the exe program. You will need to re-download everything in order for it to work. Thanks for the report!

**Pull request closed without merging**
